var NAVTREEINDEX0 =
{
"index.html":[],
"index.html#adriatico":[0,5],
"index.html#arco":[0,2],
"index.html#autotoc_md1":[0],
"index.html#autotoc_md2":[1],
"index.html#autotoc_md3":[2],
"index.html#bacarando":[0,3],
"index.html#bakaro":[0,1],
"index.html#barcollo":[0,10],
"index.html#bocon":[0,12],
"index.html#fiore":[0,8],
"index.html#lele":[0,0],
"index.html#magna":[0,9],
"index.html#merca":[0,11],
"index.html#mori":[0,7],
"index.html#portego":[0,6],
"index.html#schiavi":[0,4],
"pages.html":[]
};
